DROP TABLE IF EXISTS dbo.actionTicket;
DROP TABLE IF EXISTS dbo.catalog;
DROP TABLE IF EXISTS dbo.employee;
DROP TABLE IF EXISTS dbo.operation;
DROP TABLE IF EXISTS dbo.operationSpecification;
DROP TABLE IF EXISTS dbo.orderOperation;
DROP TABLE IF EXISTS dbo.packVariant;
DROP TABLE IF EXISTS dbo.role;
DROP TABLE IF EXISTS dbo.ticket;
